### ISSUE TITLE
Verbose failed checks

### ISSUE THREAD

**Issue by jgonyea** [zrrrzzt/node-wcag-pdf#55]
Is there a way of finding out what check failed beyond just a count?  I'm trying to normalize the results between this module and Adobe Acrobat's checker, but they're not matching.

Thanks.

**Comment by zrrrzzt** [comment]
How would you like this module's response to look like meet your needs?

It it just a convenience wrapper for the [eiii pdf checker](http://checkers.eiii.eu/en/pdfcheck) so a detailed response can be found by following the `resultUrl` from the response.

I guess it could be possible to parse the complete response from that page and include the highlights in the module response.
